baseURL = "https://mikan.github.io/"
languageCode = "ja-jp"
weight = 1
title = "Yutaka ğŸŠ Kato"
publishDir = "public"
theme= "hugo-bootstrap-premium"
hasCJKLanguage = true
enableemoji = true
paginate = 10
paginatePath = "page"
disqusShortname = "kagaorange"

[permalinks]
	post = "/:year/:month/:day/:filename/"
	code = "/:filename/"
	
[author]
	name = "Yutaka Kato"
	email = "mikan@aomikan.org"
	
[params.theme]
	name = "sandstone"
  
[params]
	BrandImage = "/logo.png"
	brand = "Yutaka ğŸŠ Kato"
	topline = "Yutaka Kato ã®æŠ€è¡“ãƒ–ãƒ­ã‚°ã§ã™ã€‚"
	footline = "Copyright&copy; <a href='/about/'>Yutaka Kato</a>"
	showRightSidebar = true
	googleAnalytics = "UA-68709286-1"
	sumomeid = "7376c112ca70badebd8ee83050033a40afd51c35656127efca6d0e2f5b1f09c2"
	highlight = "default"
	twitter  = "kagaorange"
	linkedin = "yutakakato"
	github   = "mikan"
	customCSS = ["/css/mikan.css"]
	
[[menu.main]]
	name = "Home"
	identifier = "home"
	url = "/"
	weight = -200
	pre = "<i class='fa fa-home'></i>"

[[menu.main]]
	name = "Archives"
	identifier = "archives"
	url = "/post/"
	weight = -180
	pre = "<i class='fa fa-archive'></i>"

[[menu.main]]
	name = "Seminars"
	identifier = "seminars"
	url = "/seminars/"
	weight = -160
	pre = "<i class='fa fa-users'></i>"
	
[[menu.main]]
	name = "Bookshelf"
	identifier = "bookshelf"
	url = "/bookshelf/"
	weight = -140
	pre = "<i class='fa fa-book'></i>"

[[menu.main]]
	name = "Tools"
	identifier = "tools"
	url = "/tools/"
	weight = -120
	pre = "<i class='fa fa-cut'></i>"

[[menu.main]]
	name = "About"
	identifier = ""
	url = "/about/"
	weight = -100
	pre = "<i class='fa fa-info-circle'></i>"
